name: Go build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # - name: Set private packages
      #   run: go env -w GOPRIVATE=github.com/teonet-go/teonews-dbcli

      - name: Change Github URL in git config
        env:
          USER: ${{ secrets.USER }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: git config --global url."https://$USER:$PERSONAL_TOKEN@github.com".insteadOf "https://github.com"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
